# Generated by Django 5.2.1 on 2025-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
